### ISSUE TITLE
Build failure on Ubuntu 16.04

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leo_erasure#2]
I've found build failure on ubuntu-16.04 as below:
- [leo-erasure-build-error.log.txt](https://github.com/leo-project/leo_erasure/files/425205/leo-erasure-build-error.log.txt)
- OS info:

```
$ uname -a
Linux ubuntu1604d 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by windkit** [comment]
PR on JErasure
https://github.com/leo-project/jerasure/pull/5

**Comment by windkit** [comment]
Related to Issue https://github.com/leo-project/leofs/issues/488

**Comment by yosukehara** [comment]
I've tested your JErasure's PRm then it was merged into [feature/ubuntu1604-support](https://github.com/leo-project/jerasure/tree/feature/ubuntu1604-support) to check others, `ubuntu-14.04`, `CentOS-6/7`, `FreeBSD` and `SmartOS`.

Thanks.

**Comment by yosukehara** [comment]
We fixed this issue.
